name: manage-azure-policy-c6e8d9d6
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'PolicyTest/policies/Apply_Diagnostic_Settings_for_Microsoft.OperationalInsights/workspaces_to_a_Log_Analytics_Workspacedsf_46c5d641-e317-437f-abd7-2a298895f78c/**'
#      - .github/workflows/manage-azure-policy-c6e8d9d6.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_c6e8d9d6}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          PolicyTest/policies/Apply_Diagnostic_Settings_for_Microsoft.OperationalInsights/workspaces_to_a_Log_Analytics_Workspacedsf_46c5d641-e317-437f-abd7-2a298895f78c/**
